[package]
name = "fewkz/froact"
description = " Wrapper around Roact & Roact Hooks to simplify UI development"
version = "0.1.3"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]
include = ["froact.lua", "froactful.lua", "default.project.json", "LICENSE", "README.md", "wally.toml"]